title: Save vs. Total Party Kill
author: Ramanan Sivaranjan

highlighter: false

permalink: /:categories/:title/

relative_permalinks: true

paginate: 10

exclude: ['Makefile', 'README.md', 'new.rb', 'new_post_template.md']

tag_title_prefix: '#'
tag_title_suffix: ''

markdown: 'kramdown'

defaults:
  -
    scope:
        path: "masters-of-carcosa"
        type: "pages"
    values:
      layout: "carcosa_recap"
  -
    scope:
        path: "masters-of-carcosa/wilderness"
        type: "pages"
    values:
      layout: "carcosa_wilderness"