name = "blogroll-worker"
main = "src/index.js"
compatibility_date = "2024-01-01"

[triggers]
crons = ["0 * * * *"]

[[kv_namespaces]]
binding = "BLOGROLL_KV"
id = "f3fa0a5a15ce4214b68d29068c24b3ac"
preview_id = "b3794ed983bc495f914a1cb7b1443263"

[[ratelimits]]
name = "RATE_LIMITER"
namespace_id = "1001"
  [ratelimits.simple]
  limit = 60,
  period = 60
