name = "blogroll-worker"
main = "src/index.js"
compatibility_date = "2024-01-01"

[triggers]
crons = ["0 */3 * * *"]

[[kv_namespaces]]
binding = "BLOGROLL_KV"
id = "PLACEHOLDER_KV_ID"
preview_id = "PLACEHOLDER_KV_PREVIEW_ID"
